### PR TITLE
Bibindex:  Native Fulltext index Textify  Doc

### PR DESCRIPTION
**Pull request by chokribr**
BibIndex: native fulltext index textification
 
* FIX Enables native fulltext indexing by explicitly extracting text when using the BibDoc
  interface. (closes #3708) (closes #3690), (closes #2576)

### CODE REVIEW

**Comment by kaplun** [comment]
LGTM!

**Comment by kaplun** [comment]
Can you just amend the commit log to respect the current conventions:
```
BibIndex: native fulltext index textification
 
* FIX Enables native fulltext indexing by explicitly extracting text when using the BibDoc
  interface. (closes #3708) (closes #3690), (closes #2576)
```

**Review by chokribr — COMMENTED** [review]
ok

**Comment by kaplun** [comment]
Sorry, I meant re-send your PR with the amended commit log :smile:

**Comment by tiborsimko** [comment]
Note that this PR is made against @chokribr's personal clone... Please submit a new PR against upstream repository https://github.com/inveniosoftware/invenio

**Comment by kaplun** [comment]
Thanks @tiborsimko I haven't noticed the URL :+1:

**Comment by chokribr** [comment]
please find the PR [#3733](https://github.com/inveniosoftware/invenio/pull/3733)

**Pull request merged**
